### ISSUE TITLE
Danmaku subtiles doesn't work correctly with --embed-sub

### ISSUE THREAD

**Issue by anounyym1** [animelover1984/youtube-dl#11]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.07.28**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'best', 'https://www.nicovideo.jp/watch/sm33078232', '--ignore-config', '--write-sub', '--all-subs', '--embed-subs', '--merge-output-format', 'mkv']
[debug] Encodings: locale cp932, fs utf-8, out utf-8, pref cp932
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.7.9 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.3.1-2020-09-21-full_build-www.gyan.dev, ffprobe 4.3.1-2020-09-21-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Proxy map: {}
[niconico] sm33078232: Downloading video info page
[niconico] sm33078232: Downloading HTML5 player webpage
[niconico] sm33078232: Downloading JSON metadata for h264_2000kbps_720p-aac_192kbps
[niconico] sm33078232: Downloading JSON metadata for h264_1600kbps_540p-aac_192kbps
[niconico] sm33078232: Downloading JSON metadata for h264_600kbps_360p-aac_192kbps
[niconico] sm33078232: Downloading JSON metadata for h264_300kbps_360p-aac_192kbps
[niconico] sm33078232: Downloading JSON metadata for h264_2000kbps_720p-aac_64kbps
[niconico] sm33078232: Downloading JSON metadata for h264_1600kbps_540p-aac_64kbps
[niconico] sm33078232: Downloading JSON metadata for h264_600kbps_360p-aac_64kbps
[niconico] sm33078232: Downloading JSON metadata for h264_300kbps_360p-aac_64kbps
[niconico] sm33078232: Downloading comments from thread 1/1 (en)
[niconico] sm33078232: Downloading comments from thread 1/1 (jp)
[niconico] sm33078232: Downloading comments from thread 1/1 (cn)
[info] Writing video subtitles to: 駄天的下界生活-sm33078232.danmaku-en.ass
[info] Writing video subtitles to: 駄天的下界生活-sm33078232.danmaku-jp.ass
[info] Writing video subtitles to: 駄天的下界生活-sm33078232.danmaku-cn.ass
[debug] Invoking downloader on 'https://vodedge044.dmc.nico/vod/ht2_nicovideo/nicovideo-sm33078232_b7f924869a6e953300b505163a71656171ff586305324796a881ed47ca9ff4c6?ht2_nicovideo=6-oKavgj7hbR_1601942612010.8esx2gjdjo_qhr6tx_25ae2r029lr90'
[download] Heartbeat with 15.0 second interval...
[download] Destination: 駄天的下界生活-sm33078232.mp4
[download] 100% of 27.68MiB in 00:36
[ffmpeg] Embedding subtitles in '駄天的下界生活-sm33078232.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:駄天的下界生活-sm33078232.mp4" -i "file:駄天的下界生活-sm33078232.danmaku-en.ass" -i "file:駄天的下界生活-sm33078232.danmaku-jp.ass" -i "file:駄天的下界生活-sm33078232.danmaku-cn.ass" -map 0 -c copy -map "-0:s" -map "-0:d" "-c:s" mov_text -map "1:0" "-metadata:s:s:0" "language=dan" -map "2:0" "-metadata:s:s:1" "language=dan" -map "3:0" "-metadata:s:s:2" "language=dan" "file:駄天的下界生活-sm33078232.temp.mp4"
Deleting original file 駄天的下界生活-sm33078232.danmaku-en.ass (pass -k to keep)
Deleting original file 駄天的下界生活-sm33078232.danmaku-jp.ass (pass -k to keep)
Deleting original file 駄天的下界生活-sm33078232.danmaku-cn.ass (pass -k to keep)

```

## Description

Embedding danmaku subtitles doesn't seem to work correctly, I tested with mp4 container since "--merge-output-format mkv" doesn't seem to have any effect for nicovideo downloads.
I assume ffmpeg should copy subtitles instead of current "-c:s mov_text"  https://github.com/animelover1984/youtube-dl/blob/3d9cacbeccaa46aa208eeae2a89a4ec05004fd8f/youtube_dl/postprocessor/ffmpeg.py#L419

Also ffmpeg seems to cut subtitle language from "danmaku-jp" to dan.

**Comment by bbepis** [comment]
Both issues have been fixed in https://github.com/animelover1984/youtube-dl/commit/e23db97dd92e22b038feaa82742dab3d28bcb181 and https://github.com/animelover1984/youtube-dl/commit/7758c0ab22ef3cf6922e63e0936703d8c611f214

Subtitles not being applied to `--merge-output-format mkv` is because the targeted NND stream is a stream that does not need to be recombined, and therefore stays as mp4
This confuses youtube-dl and does not apply the subtitles as a result

However the implementation for forcibly changing the container format for atomic streams is shoddy at best: https://github.com/animelover1984/youtube-dl/commit/e23db97dd92e22b038feaa82742dab3d28bcb181#diff-1b2853e5064a94fd0e0ad0caf177f4a5c67712f5919839475566fa90ccf46eeaR389

I'll leave this ticket open until a proper implementation is done by creating another postprocessor

**Comment by bbepis** [comment]
Fixed in https://github.com/animelover1984/youtube-dl/commit/aa1d0b09e258b4c0873ef90f3b140de541576afe
Add `--remux mkv` as a command line option
