### ISSUE TITLE
No installation instructions for this fork.

### ISSUE THREAD

**Issue by vsr3y** [animelover1984/youtube-dl#20]
Hi, I'm trying to find out how to use this fork of youtube-dl. I already have the official youtube-dl downloaded. I noticed that installation instructions refer to the official release with no mentions of additional instructions for this particular fork.

Thank you in advance for explaining how to install this fork!

**Comment by AplhaSlayer1964** [comment]
you run it the same way as the normal youtube-dl

**Comment by vsr3y** [comment]
I'm running windows so executable download link from yt-dl.org in the installation description is your fork's version, not the main youtube-dl repo's one?

**Comment by bbepis** [comment]
The .exe is very out of date and I may not make another as it's getting very difficult to create them with the increased pip package requirements.

Before you do anything, you need to have Python 3.7 or later installed. FFmpeg and FFprobe are hard requirements to have in your PATH directory (FFprobe is bundled with FFmpeg

You need to navigate to the downloaded repository in CMD, and run this command to install dependencies:

`pip install -r requirements.txt`

Then to run the fork, you just need to use this:

`python youtube_dl\__main__.py <arguments>`

(change backslash to forward slash on unix systems)

**Comment by bbepis** [comment]
#17 also outlines a way that should also be available however for reasons I haven't figured out yet doesn't work right now.

**Comment by shananyan** [comment]
I'm using windows. It works just fine for me. I'm able to download streams from live2.nico. (You're doing god work bbepis)

Download youtube-dl_2020.0824m_x64.7z > extract in a folder. Copy ffmpeg.exe, ffplay.exe & ffprove.exe. into the same folder. Then you can run youtube-dl command from CMD.

https://i.imgur.com/LD4yfz7.png

**Comment by pukkandan** [comment]
@vsr3y If you have `py` (python3), `pip` and `git` installed, just run:

    python3 -m pip install requests mutagen websockets git+https://github.com/animelover1984/youtube-dl

**Comment by bbepis** [comment]
@RobomiYumi 
> I'm using windows. It works just fine for me. I'm able to download streams from live2.nico. (You're doing god work bbepis)

Yes the .exe version still works, however it's 5 months out of date. It's missing some new features (such as downloading NND livestream comments and generally improved livestream metadata extraction)

**Comment by vsr3y** [comment]
Thanks to everybody who made this work!

@pukkandan 

The command error'd for some reason.

C:\Users\Zeckro\Documents\Other Applications>py -m pip install requestd mutagen websockets git+https://github.com/animelover1984/youtube-dl
Collecting git+https://github.com/animelover1984/youtube-dl
  Cloning https://github.com/animelover1984/youtube-dl to c:\users\zeckro\appdata\local\temp\pip-req-build-iajh1t49
  Running command git clone -q https://github.com/animelover1984/youtube-dl 'C:\Users\Zeckro\AppData\Local\Temp\pip-req-build-iajh1t49'
ERROR: Could not find a version that satisfies the requirement requestd (from versions: none)
ERROR: No matching distribution found for requestd

@bbepis 

I cloned the repo:

> git clone https://github.com/animelover1984/youtube-dl
> cd youtube-dl
> pip install -r requirements.txt

I put FFmpeg and FFprobe in PATH directory but CMD still throws an error 
(youtube_dl.utils.PostProcessingError: ffprobe/avprobe not found. Please install one.) 
so I installed FFmpeg directly (via Chocolatey for Windows on my part):

https://stackoverflow.com/questions/30770155/ffprobe-or-avprobe-not-found-please-install-one

And it works! No errors on NicoNico and bilibili downloads!

Note: I use --embed-subs for Danmaku subtitles so it doesn't have to separate into different .ass subtitles files in case the video has comments w/ multiple languages.
(--write-sub --all-subs --embed-subs)

@RobomiYumi 

Although I got it working now, I'd like to ask where you got that 7zip file (youtube-dl_2020.0824m_x64.7z), because I haven't seen one with that name before. I'd like to know which source I overlooked in my digging.

**Comment by bbepis** [comment]
> Although I got it working now, I'd like to ask where you got that 7zip file (youtube-dl_2020.0824m_x64.7z), because I haven't seen one with that name before. I'd like to know which source I overlooked in my digging.

It's in the releases tab in this repo.

> I put FFmpeg and FFprobe in PATH directory but CMD still throws an error

Only thing I can think of is that if you edited the PATH variable, you need to restart CMD too since it only reads the system PATH on launch.

Glad to hear that you got it working though.

**Comment by vsr3y** [comment]
@bbepis 

I completely forgot the right side of the repo page! I kept looking at the left side on the filenames for releases! Found it.

I also completely forgot about CMD. Maybe it's redundant but I tried uninstalling components from chocolatey, put the directory to executables in PATH, restarting CMD to make sure it works this way as well. And it works! 

Also, on my note for using --embed-subs, I found that VLC displays one subtitles at a time when embedded but displays all subtitles files extracted when not embedded. Playing VLC with double subtitles is doable but also a pain of setting things manually for each video and doesn't work for Danmaku subs in 3+ languages. I guess it's better not to embed.

**Comment by pukkandan** [comment]
> py -m pip install requestd mutagen websockets git+https://github.com/animelover1984/youtube-dl

`requests`, not `requestd`

**Comment by pukkandan** [comment]
>  I tried python youtube_dl\__main__.py -U but it doesn't work, probably because I downloaded it with Git and not actual youtube-dl.exe.

`-U` only works for the original youtube-dl, not for any fork

**Comment by bbepis** [comment]
Closing this ticket as it seems to be resolved. Pinning it as well though since it contains useful information for future users

**Comment by yuusakuri** [comment]
I have created a scoop manifest for installing and uninstalling this fork.
However, in order to avoid a file name conflict with the original, the exe file name is `youtube-dl-animelover1984.exe`.

https://github.com/yuusakuri/scoop-bucket

**Comment by slycordinator** [comment]
With regard to the instructions, it feels disjointed having the Readme for this fork to have the Installation section tell one how to install the upstream youtube-dl project instead of the fork.

I realize that most users won't need the modifications that you've made, but someone who wants those modifications is likely to follow the Readme installation instructions and be confused that they ended up without those changes.
