### ISSUE TITLE
Youtube-dl not working on windows. Am I doing something wrong?

### ISSUE THREAD

**Issue by angentanewbe** [animelover1984/youtube-dl#21]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am trying to download a video file and I get a error "YouTube said: Unable to extract video data". the detailed verbose is posted below.
I downloaded the "youtube-dl_2020.08.24m_x64" file and extracted in a folder and I copied ffmpeg ffplay ffprobe and atomicparsley into the directory. then I tried to execute commands are error happened. I have python 3.8 installed in case its required also the main youtube-dl is working fine and downloading the video. I want to use this version to scrape the comments.

here is the detailed verbose :
youtube-dl --ignore-config -v --get-comments https://www.youtube.com/watch?v=bCfY9ZWOT2E
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', '--get-comments', 'https://www.youtube.com/watch?v=bCfY9ZWOT2E']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.7.9 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] bCfY9ZWOT2E: Downloading webpage
ERROR: bCfY9ZWOT2E: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyc", line 798, in extract_info
  File "youtube_dl\extractor\common.pyc", line 531, in extract
  File "youtube_dl\extractor\youtube.pyc", line 1898, in _real_extract
youtube_dl.utils.ExtractorError: bCfY9ZWOT2E: YouTube said: Unable to extract video data

**Comment by bbepis** [comment]
The .exe version is very out of date and no longer works with Youtube.

You need to download the source code of the repository, extract it and then follow these instructions: https://github.com/animelover1984/youtube-dl/issues/20#issuecomment-761728143

**Comment by angentanewbe** [comment]
> 
> 
> The .exe version is very out of date and no longer works with Youtube.
> 
> You need to download the source code of the repository, extract it and then follow these instructions: [#20 (comment)](https://github.com/animelover1984/youtube-dl/issues/20#issuecomment-761728143)

please explain in detail. how to do that because when I extract the source code file and use cmd to nevigate there and try to run command it does nothing.

this is what I tried

pip install -r requirements.txt
Requirement already satisfied: websockets in c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 1)) (8.1)

F:\a\youtube-dl-2020.08.24m>python youtube_dl\__main__.py -F https://www.youtube.com/watch?v=bCfY9ZWOT2E

F:\a\youtube-dl-2020.08.24m>python youtube_dl\__main__.py https://www.youtube.com/watch?v=bCfY9ZWOT2E

F:\a\youtube-dl-2020.08.24m>python youtube_dl\__main__.py youtube-dl https://www.youtube.com/watch?v=bCfY9ZWOT2E

F:\a\youtube-dl-2020.08.24m>python youtube_dl\__main__.pyhttps://www.youtube.com/watch?v=bCfY9ZWOT2E

**Comment by pukkandan** [comment]
python -m youtube_dl -F https://www.youtube.com/watch?v=bCfY9ZWOT2E

**Comment by angentanewbe** [comment]
> python -m youtube_dl -F https://www.youtube.com/watch?v=bCfY9ZWOT2E

not working.

**Comment by pukkandan** [comment]
what is the error message?

**Comment by angentanewbe** [comment]
> what is the error message?

It just jumps to the new line of command. Nothing happens.

**Comment by pukkandan** [comment]
That shouldn't happen. If the package can't be found, it should show error message

Check if python is correctly loading

**Comment by angentanewbe** [comment]
> 
> 
> That shouldn't happen. If the package can't be found, it should show error message
> 
> Check if python is correctly loading

I have installed python through the installer from the python.org website. is there anything else that I have to install to make it work. I can open python through the shortcut and it is working fine.

**Comment by pukkandan** [comment]
python maybe installed with the name `py` or `python3` instead of `python`. Try `where py`, `where python` and `where python3` and see which gives correct path. The use that name instead of python. You can also run `python --version` to see if python is running correctly.

**Comment by angentanewbe** [comment]
> 
> 
> python maybe installed with the name `py` or `python3` instead of `python`. Try `where py`, `where python` and `where python3` and see which gives correct path. The use that name instead of python. You can also run `python --version` to see if python is running correctly.

seems to work but I get this error

py -m youtube_dl -F https://www.youtube.com/watch?v=bCfY9ZWOT2E
[youtube] bCfY9ZWOT2E: Downloading webpage
ERROR: bCfY9ZWOT2E: YouTube said: Unable to extract video data

**Comment by pukkandan** [comment]
Give output with `-v` added

It works for me:

```
python3 -m youtube_dl -v -F https://www.youtube.com/watch?v=bCfY9ZWOT2E
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=bCfY9ZWOT2E']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.8.5 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] bCfY9ZWOT2E: Downloading webpage
[youtube] {18} signature length 106, html5 player bfb74eaf
[youtube] bCfY9ZWOT2E: Downloading player https://www.youtube.com/s/player/bfb74eaf/player_ias.vflset/en_US/base.js
[youtube] {135} signature length 106, html5 player bfb74eaf
[youtube] {244} signature length 106, html5 player bfb74eaf
[youtube] {134} signature length 106, html5 player bfb74eaf
[youtube] {243} signature length 106, html5 player bfb74eaf
[youtube] {133} signature length 106, html5 player bfb74eaf
[youtube] {242} signature length 102, html5 player bfb74eaf
[youtube] bCfY9ZWOT2E: Downloading player https://www.youtube.com/s/player/bfb74eaf/player_ias.vflset/en_US/base.js
[youtube] {160} signature length 106, html5 player bfb74eaf
[youtube] {278} signature length 106, html5 player bfb74eaf
[youtube] {140} signature length 106, html5 player bfb74eaf
[youtube] {249} signature length 106, html5 player bfb74eaf
[youtube] {250} signature length 106, html5 player bfb74eaf
[youtube] {251} signature length 106, html5 player bfb74eaf
[info] Available formats for bCfY9ZWOT2E:
format code  extension  resolution note
249          webm       audio only tiny   55k , opus @ 50k (48000Hz), 1.27MiB
250          webm       audio only tiny   72k , opus @ 70k (48000Hz), 1.68MiB
140          m4a        audio only tiny  128k , m4a_dash container, mp4a.40.2@128k (44100Hz), 3.07MiB
251          webm       audio only tiny  143k , opus @160k (48000Hz), 3.31MiB
278          webm       256x144    144p   99k , webm container, vp9, 30fps, video only, 2.22MiB
160          mp4        256x144    144p  113k , avc1.4d400c, 30fps, video only, 2.40MiB
242          webm       426x240    240p  231k , vp9, 30fps, video only, 4.87MiB
133          mp4        426x240    240p  247k , avc1.4d4015, 30fps, video only, 4.90MiB
243          webm       640x360    360p  413k , vp9, 30fps, video only, 8.78MiB
134          mp4        640x360    360p  638k , avc1.4d401e, 30fps, video only, 12.16MiB
244          webm       854x480    480p  762k , vp9, 30fps, video only, 15.88MiB
135          mp4        854x480    480p 1199k , avc1.4d401f, 30fps, video only, 23.37MiB
18           mp4        640x360    360p  697k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 16.85MiB (best)
```

**Comment by angentanewbe** [comment]
py -m youtube_dl --ignore-config -v -F https://www.youtube.com/watch?v=bCfY9ZWOT2E
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', '-F', 'https://www.youtube.com/watch?v=bCfY9ZWOT2E']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] bCfY9ZWOT2E: Downloading webpage
ERROR: bCfY9ZWOT2E: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "F:\a\youtube-dl-2020.08.24m\youtube_dl\YoutubeDL.py", line 798, in extract_info
    ie_result = ie.extract(url)
  File "F:\a\youtube-dl-2020.08.24m\youtube_dl\extractor\common.py", line 531, in extract
    ie_result = self._real_extract(url)
  File "F:\a\youtube-dl-2020.08.24m\youtube_dl\extractor\youtube.py", line 1897, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: bCfY9ZWOT2E: YouTube said: Unable to extract video data

**Comment by pukkandan** [comment]
> [debug] youtube-dl version 2020.07.28

You are using wrong youtube_dl. Are you running this from the correct folder? If you are unable to diagnose the problem, let's scrap everything and install from scratch. To do that, just run:

py -m pip uninstall youtube_dl
py -m pip install --upgrade websockets mutagen git+https://github.com/animelover1984/youtube-dl

You will need to install https://gitforwindows.org for this to work if you don't have git. But this is imo the best method to install this fork. This method allows you to use youtube_dl from any folder and, you can simply run the second command in the future to update

**Comment by angentanewbe** [comment]
> 
> 
> > [debug] youtube-dl version 2020.07.28
> 
> You are using wrong youtube_dl. Are you running this from the correct folder? If you are unable to diagnose the problem, let's scrap everything and install from scratch. To do that, just run:
> 
> ```
> py -m pip uninstall youtube_dl
> py -m pip install --upgrade websockets mutagen git+https://github.com/animelover1984/youtube-dl
> ```
> 
> You will need to install https://gitforwindows.org for this to work if you don't have git. But this is imo the best method to install this fork. This method allows you to use youtube_dl from any folder and, you can simply run the second command in the future to update

Ok let me try and give you an update on that.

**Comment by angentanewbe** [comment]
Am I supposed to run these commands in CMD or in GIt?

**Comment by angentanewbe** [comment]
in Git error is

py -m pip install --upgrade websockets mutagen git+https://github.com/animelover1984/youtube-dl
Requirement already satisfied: websockets in c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages (8.1)
Requirement already satisfied: mutagen in c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages (1.45.1)
Collecting git+https://github.com/animelover1984/youtube-dl
  Cloning https://github.com/animelover1984/youtube-dl to c:\users\username\appdata\local\temp\pip-req-build-xuetl0lg
ERROR: Command errored out with exit status 128: git clone -q https://github.com/animelover1984/youtube-dl 'C:\Users\usernamel\AppData\Local\Temp\pip-req-build-xuetl0lg' Check the logs for full command output.


In CMD error is 

py -m pip install --upgrade websockets mutagen git+https://github.com/animelover1984/youtube-dl
Requirement already satisfied: websockets in c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages (8.1)
Requirement already satisfied: mutagen in c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages (1.45.1)
Collecting git+https://github.com/animelover1984/youtube-dl
  Cloning https://github.com/animelover1984/youtube-dl to c:\users\username\appdata\local\temp\pip-req-build-olx4zy51
ERROR: Command errored out with exit status 128: git clone -q https://github.com/animelover1984/youtube-dl 'C:\Users\username\AppData\Local\Temp\pip-req-build-olx4zy51' Check the logs for full command output.

C:\Users\usernamel>Requirement already satisfied: websockets in c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages (8.1)
'Requirement' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\username>Requirement already satisfied: mutagen in c:\users\usernamel\appdata\local\programs\python\python38-32\lib\site-packages (1.45.1)
'Requirement' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\username>Collecting git+https://github.com/animelover1984/youtube-dl
'Collecting' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\username>  Cloning https://github.com/animelover1984/youtube-dl to c:\users\username\appdata\local\temp\pip-req-build-xuetl0lg
'Cloning' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\username>ERROR: Command errored out with exit status 128: git clone -q https://github.com/animelover1984/youtube-dl 'C:\Users\username\AppData\Local\Temp\pip-req-build-xuetl0lg' Check the logs for full command output.
'ERROR:' is not recognized as an internal or external command,
operable program or batch file.

**Comment by angentanewbe** [comment]
I Installed it through CMD by these commands and its working now.
git clone https://github.com/animelover1984/youtube-dl
cd youtube-dl
pip install -r requirements.txt

but I want to know --get-comments file is located in which folder because I downloaded a video and its comments the video is downloaded but I am unable to locate comments file.

py -m youtube_dl --ignore-config --get-comments https://www.youtube.com/watch?v=bCfY9ZWOT2E
[youtube] bCfY9ZWOT2E: Downloading webpage
[youtube] Comments downloaded (chain UgwDyPcZEfEHGxE5ugZ4AaABAg) 3 / ~ 252
[youtube] Comments downloaded (chain UgixvhFxAoYi2ngCoAEC) 5 / ~ 252
[youtube] Comments downloaded (chain UgimCYeFrWdYIXgCoAEC) 12 / ~ 252
[youtube] Comments downloaded (chain UggG4UhQ9tCdZ3gCoAEC) 16 / ~ 252
[youtube] Comments downloaded (chain UgjKA702GK1eiXgCoAEC) 21 / ~ 252
[youtube] Comments downloaded (chain UgjKA702GK1eiXgCoAEC) 31 / ~ 252
[youtube] Comments downloaded (chain Ugwro-iuS4TbrzhdTY54AaABAg) 60 / ~ 252
[youtube] Comments downloaded 63 / ~ 252
[youtube] Comments downloaded (chain Ugwj3xikxHO9IGeaZUB4AaABAg) 65 / ~ 252
[youtube] Comments downloaded (chain UgjEG8gjAVPmKngCoAEC) 68 / ~ 252
[youtube] Comments downloaded (chain UgzVXj1RErm3rVgT62t4AaABAg) 75 / ~ 252
[youtube] Comments downloaded (chain UggS4MmZDPMAH3gCoAEC) 87 / ~ 252
[youtube] Comments downloaded (chain UgjkdhswR_55mngCoAEC) 91 / ~ 252
[youtube] Comments downloaded 94 / ~ 252
[youtube] Comments downloaded (chain Ugyi_lsg3A8uaRVSNi54AaABAg) 95 / ~ 252
[youtube] Comments downloaded (chain UggI1oq-u2cZpngCoAEC) 112 / ~ 252
[youtube] Comments downloaded 119 / ~ 252
[youtube] Comments downloaded (chain UgwSqVdBQNL6x5f6Xs94AaABAg) 121 / ~ 252
[youtube] Comments downloaded (chain UgiZfxVCo72OdngCoAEC) 127 / ~ 252
[youtube] Comments downloaded (chain Ugx7Iiyj2gqif8wqYo94AaABAg) 139 / ~ 252
[youtube] Comments downloaded (chain Ugw10A56pBO8vGnU05d4AaABAg) 144 / ~ 252
[youtube] Comments downloaded 146 / ~ 252
[youtube] Comments downloaded (chain Ugzbqq35jR4Xy59V1ll4AaABAg) 155 / ~ 252
[youtube] Comments downloaded (chain Ugy_mXoHmuCT-P1zEX54AaABAg) 167 / ~ 252
[youtube] Comments downloaded 169 / ~ 252
[youtube] Comments downloaded (chain UgysMp8ZDPDzYctPMkx4AaABAg) 175 / ~ 252
[youtube] Comments downloaded (chain UgjbgwfA1j9wQHgCoAEC) 179 / ~ 252
[youtube] Comments downloaded (chain Ugz_3jJ2hCHxLH5mMXZ4AaABAg) 184 / ~ 252
[youtube] Comments downloaded (chain Ugj23qoBvItOrHgCoAEC) 187 / ~ 252
[youtube] Comments downloaded (chain Ugh02yLXgXYg5HgCoAEC) 192 / ~ 252
[youtube] Comments downloaded (chain Ugwm4pdWnhw6Q5a9PoZ4AaABAg) 196 / ~ 252
[youtube] Comments downloaded (chain UghuspMhFBad2XgCoAEC) 199 / ~ 252
[youtube] Comments downloaded 204 / ~ 252
[youtube] Comments downloaded (chain UghMfHKyux9bGngCoAEC) 208 / ~ 252
[youtube] Comments downloaded (chain UgxXBH_CIj5acKuDzW14AaABAg) 214 / ~ 252
[youtube] Comments downloaded (chain Ugwra66HcDd6pRfhBg14AaABAg) 228 / ~ 252
[youtube] Comments downloaded 229 / ~ 252
[youtube] Comments downloaded (chain Ugg6JkPZofcMdXgCoAEC) 232 / ~ 252
[youtube] Comments downloaded (chain UgiKbcoDoALfGXgCoAEC) 240 / ~ 252
[youtube] Comments downloaded (chain Ugx_OEpyWbi0HL3Sj514AaABAg) 244 / ~ 252
[youtube] Comments downloaded 249 / ~ 252
[youtube] Total comments downloaded 249 / ~ 252
[download] Destination: Deep Forest - Madazulu (Clip officiel)-bCfY9ZWOT2E.mp4
[download] 100% of 16.85MiB in 00:12

**Comment by pukkandan** [comment]
Glad you got it working.

The comments are saved to the info.json. To write the info to disk, you must also give it `--write-info-json`. Then you will get a file ` Deep Forest - Madazulu (Clip officiel)-bCfY9ZWOT2E.info.json` which contains the comments

**Comment by angentanewbe** [comment]
> Glad you got it working.
> 
> The comments are saved to the info.json. To write the info to disk, you must also give it `--write-info-json`. Then you will get a file ` Deep Forest - Madazulu (Clip officiel)-bCfY9ZWOT2E.info.json` which contains the comments

Thanks it is working now and the file is located now.

**Comment by angentanewbe** [comment]
Closing the issue. Because its resolved now.
