### ISSUE TITLE
Can't Download Videos, 'ImportError: No module named mutagen'

### ISSUE THREAD

**Issue by InklingGirl** [animelover1984/youtube-dl#25]
## Checklist

- [x] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.12.14**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
python __main__.py https://www.youtube.com/<INSERTVID>
Traceback (most recent call last):
  File "__main__.py", line 16, in <module>
    import youtube_dl
  File "/home/christian/youtube-dl/youtube_dl/__init__.py", line 15, in <module>
    from .options import (
  File "/home/christian/youtube-dl/youtube_dl/options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "/home/christian/youtube-dl/youtube_dl/downloader/__init__.py", line 5, in <module>
    from .hls import HlsFD
  File "/home/christian/youtube-dl/youtube_dl/downloader/hls.py", line 12, in <module>
    from .external import FFmpegFD
  File "/home/christian/youtube-dl/youtube_dl/downloader/external.py", line 14, in <module>
    from ..postprocessor.ffmpeg import FFmpegPostProcessor, EXT_TO_OUT_FORMATS
  File "/home/christian/youtube-dl/youtube_dl/postprocessor/__init__.py", line 3, in <module>
    from .embedthumbnail import EmbedThumbnailPP
  File "/home/christian/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 10, in <module>
    import mutagen
ImportError: No module named mutagen
```

## Description

Whenever I try to use this fork on Ubuntu 20.10, I receive `ImportError: No module named mutagen`, what can I do?

**Comment by pukkandan** [comment]
pip install mutagen

@bbepis when we merged this code into yt-dlp, we had made a lot of improvements, including the error handling of this very issue. You might wanna pull some of those changes back to this fork

**Comment by InklingGirl** [comment]
> ```
> pip install mutagen
> ```

```Requirement already satisfied: mutagen in ./.local/lib/python3.8/site-packages (1.45.1)```

Supposedly already installed? Still doesn't work.

**Comment by pukkandan** [comment]
It is installed in python3. You might be trying to run youtube-dl from python2. See what is the output of `which python`

**Comment by InklingGirl** [comment]
```which python``` yields ```/usr/bin/python```

Simply ```python``` yields ```Python 2.7.18 (default, Aug 24 2020, 19:12:23) 
[GCC 10.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.```

**Comment by InklingGirl** [comment]
> You might be trying to run youtube-dl from python2.

How would I do this?

**Comment by pukkandan** [comment]
Try:
```
python3 __main__.py URL
```

**Comment by InklingGirl** [comment]
> ```
> python3 __main__.py URL
> ```

Specifying python3 makes it work!
