### ISSUE TITLE
Nicovideo ERROR: No video formats found

### ISSUE THREAD

**Issue by nulv** [animelover1984/youtube-dl#29]
It seems like downloading normal Nico video doesn't work anymore, there is a "ERROR: No video formats found" message. Live stream video is still ok.

Can you confirm that downloading normal Nico video still work?

**Comment by hizukiayaka** [comment]
https://www.nicovideo.jp/watch/sm22549884
I get the same error in the video above

**Comment by animelover1984** [comment]
We're aware; this is happening on all youtube-dl repos, not just this fork. 
Niconico changed their video/audio format reporting. I don't think it's too bad to fix, but it may end up being a big pain given the current implementation of the quality extraction/heartbeat logic.

**Comment by animelover1984** [comment]
Fix is up on: https://github.com/animelover1984/youtube-dl/tree/Niconico_download_fix
I'll merge to master either tonight or tomorrow (probably). Let me know if you have any issues.

**Comment by nulv** [comment]
The fix works, thank you so much.

**Comment by CXwudi** [comment]
> Fix is up on: https://github.com/animelover1984/youtube-dl/tree/Niconico_download_fix
> It's not extensively tested. I'll merge to master either tonight or tomorrow (probably). Let me know if you have any issues.

Hi animeover1984, I am not sure is it always caused by this fix or not, but I figured that audio qualityis cut. For example, 
[Imgur](https://imgur.com/G95vftn)
The originally quality should be [this](https://imgur.com/C3EOgG5)
I used best video+best audio format.

**Comment by Kurodanii** [comment]
How exactly do i use the fix? Been looking around trying to figure it out but still don't know.

**Comment by CXwudi** [comment]
@Kurodanii https://github.com/animelover1984/youtube-dl/issues/20#issuecomment-761728143

**Comment by yuzuri** [comment]
Thanks all for all the contributors. I could use new code for niconico.

@Kurodanii 
For me, this works.
- `conda install python-dateutil`
- `pip install git+https://github.com/animelover1984/youtube-dl.git@Niconico_download_fix`
