### ISSUE TITLE
API key in public repo

### ISSUE THREAD

**Issue by Vilquid** [animelover1984/youtube-dl#46]
Hello,

Be carefull, you comitted an API key in this repo : https://github.com/animelover1984/youtube-dl/blob/74c803336b98247cc45187cb873c6983617f8b0e/youtube_dl/extractor/anvato.py#L211

**Comment by pukkandan** [comment]
It is the API key used by the site on browser

**Comment by Vilquid** [comment]
Okay

**Comment by pukkandan** [comment]
FYI, https://github.com/animelover1984/youtube-dl/issues/44#issuecomment-1087027022
